apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: arm7tdmi/spring-petclinic-jdbc:0.2
        securityContext:
          runAsUser: 1000
        ports:
        - name:  liveness-port
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - name: log-dir
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /manage/health
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 10
      volumes:
      - name: log-dir
        hostPath:
          path: /logs
          type: Directory
