apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - port: 8080
  selector:
    app: petclinic
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: petclinic
          servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: arm7tdmi/spring-petclinic-jdbc:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        command: ["sh", "-c", "java -cp /app/resources:/app/classes:/app/libs/* org.springframework.samples.petclinic.PetClinicApplication 2>&1 | tee /app/logs/app.log"]
        ports:
        - name:  liveness-port
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - name: log-dir
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /manage/health
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 10
      terminationGracePeriodSeconds: 30
      volumes:
      - name: log-dir
        hostPath:
          path: /logs
          type: Directory
